### ISSUE TITLE
HMM Decoding example

### ISSUE THREAD

**Issue by dn2015** [prnicolas/ScalaMl#2]
I bought the book Scala for Machine Learning. I tried to use HMM in one of my projects. There're unit tests (examples) to train and evaluate the a HMM, but there's no example of decoding. I tried to write some code to decode from a trained HMM (CF-3), but I keep getting index out of bound. I'm not sure if my setup for decoding is wrong or there's some issue with the Viterbi implementation. Could you provide an example of CF-3? Thanks.

**Comment by prnicolas** [comment]
The publisher and I have a scheduled update of the code next week with improved and more consistent scaladocs.  I will add a simple example of Viterbi algorithm.We are also planning on an alternative implementation of the training and Viterbi using tail recursion: Not sure about ETA.

Regards,
 Patrick R. Nicolas
http://patricknicolas.blogspot.com
 

     On Tuesday, January 20, 2015 8:45 AM, dn2015 <notifications@github.com> wrote:
   

 I bought the book Scala for Machine Learning. I tried to use HMM in one of my projects. There're unit tests (examples) to train and evaluate the a HMM, but there's no example of decoding. I tried to write some code to decode from a trained HMM (CF-3), but I keep getting index out of bound. I'm not sure if my setup for decoding is wrong or there's some issue with the Viterbi implementation. Could you provide an example of CF-3? Thanks.—

**Comment by dn2015** [comment]
Patrick,

Thank you for the update. I’m looking forward to the updated code.

Thanks.

D

**Comment by dn2015** [comment]
I really appreciate the prompt updated code and the example of running CF-3 in the unit tests as requested.
